const events = [
    {
        id: 1,
        title: { en: "City Summer Fest 🎵", ar: "مهرجان صيف المدينة 🎵" },
        description: { en: "A three-day music festival featuring local bands.", ar: "مهرجان موسيقي لمدة ثلاثة أيام يضم فرقاً محلية." },
        category: { en: "Music", ar: "موسيقى" },
        rawCategory: "music", 
        date: "2026-11-05",
        location: { en: "City Park", ar: "حديقة المدينة" },
        price: { en: "Free", ar: "مجاني" },
        image: "images/event-music-concert.jpg",
        ticketsLink: "https://tickets.com/event1",
        promoLink: "https://youtube.com/event1",
        aboutText1: { en: "This is the first paragraph about the City Summer Fest, focusing on its history and impact on the local community.", ar: "هذه هي الفقرة الأولى عن مهرجان صيف المدينة، وتفاصيل حول تاريخه وأثره على المجتمع المحلي." },
        aboutText2: { en: "The festival aims to promote emerging local talents and provide a family-friendly atmosphere.", ar: "يهدف المهرجان إلى تعزيز المواهب المحلية الناشئة وتوفير أجواء مناسبة للعائلة." },
        latitude: 40.7128,
        longitude: -74.0060
    },
    {
        id: 2,
        title: { en: "International Food Fair 🌮", ar: "معرض الطعام الدولي 🌮" },
        description: { en: "Taste dishes from around the world in one location.", ar: "تذوق أطباق من جميع أنحاء العالم في مكان واحد." },
        category: { en: "Food", ar: "طعام" },
        rawCategory: "food",
        date: "2025-11-05",
        location: { en: "Exhibition Center", ar: "مركز المعارض" },
        price: { en: "$10", ar: "10 دولارات" },
        image: "images/food-fair.jpg",
        ticketsLink: "https://tickets.com/event2",
        promoLink: "https://youtube.com/event2",
        aboutText1: { en: "Experience culinary delights from over 30 different countries and cultures.", ar: "استمتع بتجارب طعام من أكثر من 30 دولة وثقافة مختلفة." },
        aboutText2: { en: "Chefs will conduct live cooking demonstrations throughout the event.", ar: "سيجري الطهاة عروض طهي حية على مدار الحدث." },
        latitude: 40.7128,
        longitude: -74.0060
    },
    {
        id: 3,
        title: { en: "Modern Art Exhibition 🎨", ar: "معرض الفن الحديث 🎨" },
        description: { en: "Showcasing works from 20 emerging artists.", ar: "عرض أعمال فنية من 20 فناناً ناشئاً." },
        category: { en: "Arts", ar: "فنون" },
        rawCategory: "culture",
        date: "2025-11-25",
        location: { en: "City Museum", ar: "متحف المدينة" },
        price: { en: "$5", ar: "5 دولارات" },
        image: "images/art-exhibit.jpg",
        ticketsLink: "https://tickets.com/event3",
        promoLink: "https://youtube.com/event3",
        aboutText1: { en: "The exhibition focuses on contemporary themes using diverse media and installations.", ar: "يركز المعرض على الموضوعات المعاصرة باستخدام وسائط وتركيبات متنوعة." },
        aboutText2: { en: "Guided tours are available every hour in English and Arabic.", ar: "تتوفر جولات إرشادية كل ساعة باللغتين الإنجليزية والعربية." },
        latitude: 40.7128,
        longitude: -74.0060
    },
    {
        id: 4,
        title: { en: "Annual City Marathon 🏃", ar: "ماراثون المدينة السنوي 🏃" },
        description: { en: "Join the race for health and charity.", ar: "شارك في السباق من أجل الصحة والعمل الخيري." },
        category: { en: "Sports", ar: "رياضة" },
        rawCategory: "sports",
        date: "2025-12-05",
        location: { en: "Main Stadium", ar: "الملعب الرئيسي" },
        price: { en: "$20", ar: "20 دولاراً" },
        image: "images/marathon.jpg",
        ticketsLink: "https://tickets.com/event4",
        promoLink: "https://youtube.com/event4",
        aboutText1: { en: "All proceeds from registration go directly to local children's charities.", ar: "تذهب جميع عائدات التسجيل مباشرة إلى الجمعيات الخيرية المحلية للأطفال." },
        aboutText2: { en: "The route covers the city's scenic landmarks, starting and ending at the stadium.", ar: "يمر المسار بالمعالم السياحية للمدينة، بدءاً وانتهاءً بالملعب." },
        latitude: 40.7128,
        longitude: -74.0060
    },
    {
        id: 5,
        title: { en: "Community Fun Day 👨‍👩‍👧", ar: "يوم المرح المجتمعي 👨‍👩‍👧" },
        description: { en: "Games, food stalls, and entertainment for all ages.", ar: "ألعاب وأكشاك طعام وترفيه لجميع الأعمار." },
        category: { en: "Family", ar: "عائلي" },
        rawCategory: "family",
        date: "2025-12-20",
        location: { en: "City Park Pavilion", ar: "جناح حديقة المدينة" },
        price: { en: "Free", ar: "مجاني" },
        image: "images/family_day.jpg",
        ticketsLink: "https://tickets.com/event5",
        promoLink: "https://youtube.com/event5",
        aboutText1: { en: "A free event organized by the City Council to strengthen community bonds.", ar: "حدث مجاني ينظمه مجلس المدينة لتعزيز الروابط المجتمعية." },
        aboutText2: { en: "Featuring bouncy castles, face painting, and live acoustic music.", ar: "يضم قلاعاً قابلة للنفخ، ورسم على الوجه، وموسيقى أكوستيك حية." },
        latitude: 40.7128,
        longitude: -74.0060
    },
    {
    id: 6,
    title: { en: "Family Picnic Day 🧺", ar: "يوم النزهة العائلية 🧺" },
    description: { en: "Picnic games, storytelling, and outdoor fun for everyone.", ar: "ألعاب نزهة، قصص، ومتعة في الهواء الطلق للجميع." },
    category: { en: "Family", ar: "عائلي" },
    rawCategory: "family",
    date: "2025-11-15",
    location: { en: "Lakeside Garden", ar: "حديقة جانب البحيرة" },
    price: { en: "Free", ar: "مجاني" },
    image: "images/family_picnic.jpg",
    ticketsLink: "https://tickets.com/event6",
    promoLink: "https://youtube.com/event6",
    aboutText1: { en: "A free family day to enjoy nature, games, and bonding activities.", ar: "يوم مجاني للعائلة للاستمتاع بالطبيعة، والألعاب، وأنشطة تعزيز الروابط." },
    aboutText2: { en: "Includes a treasure hunt, live puppet show, and family photo spots.", ar: "يتضمن البحث عن الكنز، عرض دمى حي، وزوايا تصوير للعائلة." },
    latitude: 40.7128,
    longitude: -74.0060
},
{
    id: 7,
    title: { en: "Weekend Family Fair 🎡", ar: "معرض العائلة الأسبوعي 🎡" },
    description: { en: "Rides, food trucks, and family-friendly shows all weekend.", ar: "ألعاب، شاحنات طعام، وعروض مناسبة للعائلة طوال عطلة الأسبوع." },
    category: { en: "Family", ar: "عائلي" },
    rawCategory: "family",
    date: "2025-10-18",
    location: { en: "Downtown Square", ar: "ساحة وسط المدينة" },
    price: { en: "Free Entry", ar: "دخول مجاني" },
    image: "images/family_fair.jpg",
    ticketsLink: "https://tickets.com/event7",
    promoLink: "https://youtube.com/event7",
    aboutText1: { en: "A lively weekend fair with activities to entertain kids and parents alike.", ar: "معرض حي لعطلة نهاية الأسبوع مع أنشطة تسلي الأطفال والآباء على حد سواء." },
    aboutText2: { en: "Enjoy carousel rides, magic shows, and food stalls with treats for everyone.", ar: "استمتع بركوب الدوّامة، عروض السحر، وأكشاك الطعام مع وجبات للجميع." },
    latitude: 40.7128,
    longitude: -74.0060
},
{
    id: 8,
    title: { en: "Evening Jazz Night 🎷", ar: "ليلة الجاز المسائية 🎷" },
    description: { en: "Smooth jazz performances under the stars.", ar: "عروض جاز سلسة تحت النجوم." },
    category: { en: "Music", ar: "موسيقى" },
    rawCategory: "music",
    date: "2025-11-05",
    location: { en: "Riverside Amphitheater", ar: "مسرح على ضفاف النهر" },
    price: { en: "$10", ar: "10$" },
    image: "images/jazz_night.jpg",
    ticketsLink: "https://tickets.com/event8",
    promoLink: "https://youtube.com/event8",
    aboutText1: { en: "A cozy evening with live jazz bands and local artists.", ar: "أمسية دافئة مع فرق جاز حية وفنانيين محليين." },
    aboutText2: { en: "Perfect for music lovers to unwind and enjoy the melody.", ar: "مثالي لعشاق الموسيقى للاسترخاء والاستمتاع بالألحان." },
    latitude: 40.7128,
    longitude: -74.0060
},
{
    id: 9,
    title: { en: "Rock & Roll Festival 🎸", ar: "مهرجان الروك أند رول 🎸" },
    description: { en: "High-energy rock bands and live stage performances.", ar: "فرق روك عالية الطاقة وعروض حية على المسرح." },
    category: { en: "Music", ar: "موسيقى" },
    rawCategory: "music",
    date: "2025-12-12",
    location: { en: "City Arena", ar: "ساحة المدينة" },
    price: { en: "$25", ar: "25$" },
    image: "images/rock_festival.jpg",
    ticketsLink: "https://tickets.com/event9",
    promoLink: "https://youtube.com/event9",
    aboutText1: { en: "An electrifying night for rock fans with multiple bands performing.", ar: "ليلة مثيرة لعشاق الروك مع عروض لعدة فرق." },
    aboutText2: { en: "Food, drinks, and merchandise stalls available for attendees.", ar: "أكشاك طعام، مشروبات، وتذكارات متاحة للحضور." },
    latitude: 40.7128,
    longitude: -74.0060
},
{
    id: 10,
    title: { en: "City Marathon 🏃‍♂️", ar: "ماراثون المدينة 🏃‍♂️" },
    description: { en: "Run through the city streets and enjoy a healthy competition.", ar: "اركض في شوارع المدينة واستمتع بمنافسة صحية." },
    category: { en: "Sports", ar: "رياضة" },
    rawCategory: "sports",
    date: "2025-10-25",
    location: { en: "Main Square", ar: "الساحة الرئيسية" },
    price: { en: "Free Registration", ar: "تسجيل مجاني" },
    image: "images/marathon.jpg",
    ticketsLink: "https://tickets.com/event10",
    promoLink: "https://youtube.com/event10",
    aboutText1: { en: "Open to all ages and skill levels, promoting fitness and fun.", ar: "مفتوح لجميع الأعمار والمستويات، لتعزيز اللياقة والمتعة." },
    aboutText2: { en: "Finishers receive medals and refreshments at the end.", ar: "يحصل المشاركون على ميداليات ومشروبات في النهاية." },
    latitude: 40.7128,
    longitude: -74.0060
},
{
    id: 11,
    title: { en: "Family Soccer Tournament ⚽", ar: "بطولة كرة القدم العائلية ⚽" },
    description: { en: "Friendly matches for families to play together.", ar: "مباريات ودية للعائلات للعب معًا." },
    category: { en: "Sports", ar: "رياضة" },
    rawCategory: "sports",
    date: "2025-11-30",
    location: { en: "City Sports Complex", ar: "مجمع المدينة الرياضي" },
    price: { en: "Free Entry", ar: "دخول مجاني" },
    image: "images/family_soccer.jpg",
    ticketsLink: "https://tickets.com/event11",
    promoLink: "https://youtube.com/event11",
    aboutText1: { en: "Encouraging family bonding through fun and friendly competition.", ar: "تشجيع الروابط العائلية من خلال المنافسة الممتعة والودية." },
    aboutText2: { en: "Includes prizes for best teamwork and fair play.", ar: "يشمل جوائز لأفضل تعاون وروح رياضية." },
    latitude: 40.7128,
    longitude: -74.0060
},
{
    id: 12,
    title: { en: "History Museum Tour 🏛️", ar: "جولة في متحف التاريخ 🏛️" },
    description: { en: "Explore ancient artifacts and historical exhibits.", ar: "استكشف التحف القديمة والمعارض التاريخية." },
    category: { en: "Museum", ar: "متاحف" },
    rawCategory: "museum",
    date: "2025-10-10",
    location: { en: "City History Museum", ar: "متحف تاريخ المدينة" },
    price: { en: "$5", ar: "5$" },
    image: "images/history_museum.jpg",
    ticketsLink: "https://tickets.com/event12",
    promoLink: "https://youtube.com/event12",
    aboutText1: { en: "Guided tours available for families and students.", ar: "جولات مرشدة متاحة للعائلات والطلاب." },
    aboutText2: { en: "Discover fascinating stories behind each exhibit.", ar: "اكتشف القصص المدهشة وراء كل قطعة." },
    latitude: 40.7128,
    longitude: -74.0060
},
{
    id: 13,
    title: { en: "Art Museum Evening 🎨", ar: "أمسية في متحف الفن 🎨" },
    description: { en: "Enjoy contemporary art exhibitions and live sketching sessions.", ar: "استمتع بمعارض الفن المعاصر وجلسات رسم مباشرة." },
    category: { en: "Museum", ar: "متاحف" },
    rawCategory: "museum",
    date: "2025-11-22",
    location: { en: "Downtown Art Museum", ar: "متحف الفن في وسط المدينة" },
    price: { en: "Free Entry", ar: "دخول مجاني" },
    image: "images/art_museum.jpg",
    ticketsLink: "https://tickets.com/event13",
    promoLink: "https://youtube.com/event13",
    aboutText1: { en: "Perfect evening for art lovers to explore new artists.", ar: "أمسية مثالية لعشاق الفن لاستكشاف فنانين جدد." },
    aboutText2: { en: "Includes live music and refreshments in the museum garden.", ar: "يشمل موسيقى حية ومشروبات في حديقة المتحف." },
    latitude: 40.7128,
    longitude: -74.0060
},
{
    id: 14,
    title: { en: "Modern Arts Gala 🎨", ar: "أمسية الفن الحديث 🎨" },
    description: { en: "A showcase of modern art from local artists.", ar: "عرض للفن الحديث من فنانين محليين." },
    category: { en: "Arts & Culture", ar: "الفنون والثقافة" },
    rawCategory: "arts",
    date: "2025-11-10",
    location: { en: "City Art Center", ar: "مركز الفن بالمدينة" },
    price: { en: "Free", ar: "مجاني" },
    image: "images/modern_art.jpg",
    ticketsLink: "https://tickets.com/event14",
    promoLink: "https://youtube.com/event14",
    aboutText1: { en: "Enjoy modern art pieces by emerging local artists.", ar: "استمتع بأعمال الفن الحديث لفنانين محليين ناشئين." },
    aboutText2: { en: "Live performances and interactive art stations included.", ar: "تشمل عروض حية ومحطات فن تفاعلية." },
    latitude: 40.7128,
    longitude: -74.0060
}

];

window.events = events;






